{
 "title": "Prediction Analytics",
 "tags": [ "seldon" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "label_values(seldon_api_engine_client_requests_seconds_count,deployment_name)"
   },
   {
    "name": "predictor",
    "query": "label_values(seldon_api_engine_client_requests_seconds_count,predictor_name)"
   },
   {
    "name": "version",
    "query": "label_values(seldon_api_engine_client_requests_seconds_count,predictor_version)"
   },
   {
    "name": "model_name",
    "query": "label_values(seldon_api_engine_client_requests_seconds_count,model_name)"
   },
   {
    "name": "model_image",
    "query": "label_values(seldon_api_engine_client_requests_seconds_count,model_image)"
   },
   {
    "name": "model_version",
    "query": "label_values(seldon_api_engine_client_requests_seconds_count,model_version)"
   }
  ]
 },
 "panels": [
  { "title": "Heading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Seldon Core API Dashboard</span>\n</div>"
  },
  { "title": "Global Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Global Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_engine_client_requests_seconds_count[1m])),0.001)"
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_engine_client_requests_seconds_count{status!~\"5.*\"}[1m])) / sum(rate(seldon_api_engine_client_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_engine_client_requests_seconds_count{status=~\"4.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_engine_client_requests_seconds_count{status=~\"5.*\"}[1m])) "
    }
   ]
  },
  { "title": "Deployment Counts $deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "deployment" },
  {
   "title": "Request Rate ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_engine_client_requests_seconds_count{deployment_name=~'$deployment'}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_engine_client_requests_seconds_count{deployment_name=~\"$deployment\",status!~\"5.*\"}[1m])) / sum(rate(seldon_api_engine_client_requests_seconds_count{deployment_name=~\"$deployment\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_engine_client_requests_seconds_count{deployment_name=~\"$deployment\",status=~\"4.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xxs ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_engine_client_requests_seconds_count{deployment_name=~\"$deployment\",status=~\"5.*\"}[1m]))"
    }
   ]
  },
  { "title": "Deployment Counts $deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Request Rate ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_engine_client_requests_seconds_count{deployment_name=~'$deployment'}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_engine_client_requests_seconds_count{deployment_name=~\"$deployment\",status!~\"5.*\"}[1m])) / sum(rate(seldon_api_engine_client_requests_seconds_count{deployment_name=~\"$deployment\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_engine_client_requests_seconds_count{deployment_name=~\"$deployment\",status=~\"4.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xxs ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_engine_client_requests_seconds_count{deployment_name=~\"$deployment\",status=~\"5.*\"}[1m]))"
    }
   ]
  },
  { "title": "Models", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Models</span>\n</div>"
  },
  { "title": "Model Metrics $model_image", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "model_image" },
  {
   "title": "Reqs/sec to $model_image",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(seldon_api_engine_client_requests_seconds_count{model_name=~\".*\",model_version=~\".*\",model_image=~\".*\",predictor_name=~\".*\",predictor_version=~\".*\"}[1m])) by (model_name,predictor_name,predictor_version,model_image,model_version,service)",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}}"
    }
   ]
  },
  {
   "title": "$model_image Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(seldon_api_engine_client_requests_seconds_bucket{uri=~\".*[Pp]redict\", model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}: {{model_version}} (p50)"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(seldon_api_engine_client_requests_seconds_bucket{uri=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p75)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(seldon_api_engine_client_requests_seconds_bucket{uri=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version, service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}}  {{service}} (p90)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(seldon_api_engine_client_requests_seconds_bucket{uri=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(seldon_api_engine_client_requests_seconds_bucket{uri=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p99)"
    }
   ]
  },
  {
   "title": " $model_image Classification",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "true_pos_total{deployment_name=~\".*\",predictor_name=~\".*\",predictor_version=~\".*\",model_image=~\".*\",model_version=~\".*\",model_name=~\".*\"}",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}} TP"
    },
    {
     "expr": "true_neg_total{deployment_name=~\".*\",predictor_name=~\".*\",predictor_version=~\".*\",model_image=~\".*\",model_version=~\".*\",model_name=~\".*\"}",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}} TN"
    },
    {
     "expr": "false_pos_total{deployment_name=~\".*\",predictor_name=~\".*\",predictor_version=~\".*\",model_image=~\".*\",model_version=~\".*\",model_name=~\".*\"}",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}} FP"
    },
    {
     "expr": "false_neg_total{deployment_name=~\".*\",predictor_name=~\".*\",predictor_version=~\".*\",model_image=~\".*\",model_version=~\".*\",model_name=~\".*\"}",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}} FN"
    }
   ]
  },
  {
   "title": " $model_image Accuracy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "branch_accuracy{deployment_name=~\".*\",predictor_name=~\".*\",predictor_version=~\".*\",model_image=~\".*\",model_version=~\"1\\\\.3\",model_name=~\".*\"}",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}}"
    }
   ]
  },
  {
   "title": " $model_image Precision Recall",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "precision{deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_image=~\"$model_image\",model_version=~\"$model_version\",model_name=~\"$model_name\"}",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}} Precision"
    },
    {
     "expr": "recall{deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_image=~\"$model_image\",model_version=~\"$model_version\",model_name=~\"$model_name\"}",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}} Recall"
    }
   ]
  },
  {
   "title": " $model_image  F1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f1{deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_image=~\"$model_image\",model_version=~\"$model_version\",model_name=~\"$model_name\"}",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}} f1"
    }
   ]
  }
 ]
}