apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator-certified
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: seldon-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-operator.v1.1.0
  config:
    env:
    - name: USE_EXECUTOR
      value: "false"
