apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: rh-mlops-workshop-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/ltsai/rh-mlops-workshop-notebook:3.6
    from:
      kind: DockerImage
      name: quay.io/ltsai/rh-mlops-workshop-notebook:3.6
    name: "3.6"
    referencePolicy:
      type: Source
