apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-operator
  namespace: opendatahub
spec:
  channel: stable
  installPlanApproval: Automatic
  name: prometheus-operator
  source: prometheus-operator
  sourceNamespace: openshift-marketplace
  startingCSV: prometheusoperator.0.37.0